// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceServerSpec defines the desired state of ResourceServer.
type ResourceServerSpec struct {

	// A unique resource server identifier for the resource server. The identifier
	// can be an API friendly name like solar-system-data. You can also set an API
	// URL like https://solar-system-data-api.example.com as your identifier.
	//
	// Amazon Cognito represents scopes in the access token in the format $resource-server-identifier/$scope.
	// Longer scope-identifier strings increase the size of your access tokens.
	//
	// Regex Pattern: `^[\x21\x23-\x5B\x5D-\x7E]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Identifier *string `json:"identifier"`
	// A friendly name for the resource server.
	//
	// Regex Pattern: `^[\w\s+=,.@-]+$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// A list of scopes. Each scope is a key-value map with the keys name and description.
	Scopes []*ResourceServerScopeType `json:"scopes,omitempty"`
	// The user pool ID for the user pool.
	//
	// Regex Pattern: `^[\w-]+_[0-9a-zA-Z]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	UserPoolID  *string                                  `json:"userPoolID,omitempty"`
	UserPoolRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"userPoolRef,omitempty"`
}

// ResourceServerStatus defines the observed state of ResourceServer
type ResourceServerStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// ResourceServer is the Schema for the ResourceServers API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ResourceServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ResourceServerSpec   `json:"spec,omitempty"`
	Status            ResourceServerStatus `json:"status,omitempty"`
}

// ResourceServerList contains a list of ResourceServer
// +kubebuilder:object:root=true
type ResourceServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResourceServer `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ResourceServer{}, &ResourceServerList{})
}
