// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package resource_server

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Identifier, b.ko.Spec.Identifier) {
		delta.Add("Spec.Identifier", a.ko.Spec.Identifier, b.ko.Spec.Identifier)
	} else if a.ko.Spec.Identifier != nil && b.ko.Spec.Identifier != nil {
		if *a.ko.Spec.Identifier != *b.ko.Spec.Identifier {
			delta.Add("Spec.Identifier", a.ko.Spec.Identifier, b.ko.Spec.Identifier)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Scopes) != len(b.ko.Spec.Scopes) {
		delta.Add("Spec.Scopes", a.ko.Spec.Scopes, b.ko.Spec.Scopes)
	} else if len(a.ko.Spec.Scopes) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Scopes, b.ko.Spec.Scopes) {
			delta.Add("Spec.Scopes", a.ko.Spec.Scopes, b.ko.Spec.Scopes)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID) {
		delta.Add("Spec.UserPoolID", a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID)
	} else if a.ko.Spec.UserPoolID != nil && b.ko.Spec.UserPoolID != nil {
		if *a.ko.Spec.UserPoolID != *b.ko.Spec.UserPoolID {
			delta.Add("Spec.UserPoolID", a.ko.Spec.UserPoolID, b.ko.Spec.UserPoolID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.UserPoolRef, b.ko.Spec.UserPoolRef) {
		delta.Add("Spec.UserPoolRef", a.ko.Spec.UserPoolRef, b.ko.Spec.UserPoolRef)
	}

	return delta
}
